name: 2. CD - Deploy Infrastructure (Terraform)

on:
  repository_dispatch:
    types: [deploy-infrastructure] # Запускается по сигналу от CI-пайплайна

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Получаем ID нового AMI, переданного из CI-пайплайна
    env:
      NEW_AMI_ID: ${{ github.event.client_payload.ami_id }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Подключение к S3 Backend)
        run: terraform init

      - name: Terraform Taint and Plan
        # Taint помечает старый инстанс EC2 для принудительной замены. 
        run: |
          # Используем команду 'replace' вместо 'taint' для более чистого процесса
          terraform plan -input=false -out=tfplan -replace=aws_instance.minecraft
          
      - name: Terraform Apply
        # Применяем изменения
        run: terraform apply -auto-approve tfplan